# -*- coding: utf-8 -*-
"""Untitled160.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WgrZu7dbCorJAkZRS3PFqOIvDgYqkA2b
"""

import random

def fun_game(die_sides):
  """This is a game to roll a die 5 times"""
  die_rolls=[random.randint(1,die_sides) for die in range(5)]
  return die_rolls

